# Generated by Django 3.2 on 2021-05-12 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('established_date', models.DateField()),
                ('province', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.dojo')),
            ],
        ),
        migrations.AddField(
            model_name='dojo',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.operator'),
        ),
    ]
